id: 1a9323f56a3648a096b0c66b7b8bab13
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_249-The_Sutra_Teaching_the_Four_Factors-v2
  language: en
  author: ''
  volume: {}
